### ISSUE TITLE
CodeLens is performing too many requests in Github Actions

### ISSUE THREAD

**Issue by jorenham** [ninoseki/vscode-mogami#67]
### Describe the bug

When CodeLens is active and a workflow file tab has been open for a couple of minutes, the `latest: v1.2.3` inline hints turn into HTTP 403 error messages. 

The consequence of this is that cloudflare blacklisted my IP address, and regularly forces me to solve captcha's.

### Reproduction

Open a workflow config file with CodeLens active, and work on it for a minute or two. 

But honestly, I wouldn't recommend trying this (unless you like solving a lot of Cloudflare captchas, that is).

**Comment by ninoseki** [comment]
Thanks for reporting and sorry for the inconvenience.

I guess you got blocked because calling the API without PAT. So setting `vscode-mogami.gitHubPersonalAccessToken` (defaults to `null`) can be a workaround for the issue.
Meanwhile I realized that there is an issue with caching. I will fix it soon.

**Comment by jorenham** [comment]
Thanks!

BTW I forgot to mention that I have `"vscode-mogami.concurrency": 8` in the settings, which seems relevant

**Comment by ninoseki** [comment]
I think #69 and #70 mitigate this issue and I shipped it as v0.0.28.
